/* Data for the `BOMBA` table  (Records 1 - 4) */

INSERT INTO BOMBA (ID, ID_TANQUE, DESCRICAO)
VALUES (1, 1, 'BOMBA 1');

INSERT INTO BOMBA (ID, ID_TANQUE, DESCRICAO)
VALUES (2, 1, 'BOMBA 2');

INSERT INTO BOMBA (ID, ID_TANQUE, DESCRICAO)
VALUES (3, 2, 'BOMBA 3');

INSERT INTO BOMBA (ID, ID_TANQUE, DESCRICAO)
VALUES (4, 2, 'BOMBA 4');

COMMIT WORK;

